# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cea8304a677efbadb7c83042f25a2bfcc425041edf6cf0da020d09688f4088fef33b6cddb7077f1281e03bc572a12ae8412d48e291a74e6561693c5a856fb00a

test:
  secret_key_base: 73c0f9894a50a129deee593cf0f1ce3ec1e37bdb84678b441c749e9a612df2567ef6b3685f5edd3ac83171b218b1f6fc71abb04ecb698e4256c899f461ce81d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
